# Nginx as a load-balancing tier and reverse proxy
nginx:
  build: nginx/
  mem_limit: 128m
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
  expose:
    - 8000
    - 8443
    - 8001
  links:
    - consul:consul
  restart: always
  command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"

kong-database:
  image: postgres:9.4
  ports:
    - 5432
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong

kong:
  build: kong/
  restart: always
  links:
    - kong-database:kong-database
    - consul
  ports:
    - 8000
    - 8443
    - 8001
  expose:
    - 7946
    - 7946/udp
  environment:
    - DATABASE=postgres

# service discovery tier
consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  dns:
    - 127.0.0.1
